### ISSUE TITLE
Path Traversal Vulnerability

### ISSUE THREAD

**Issue by cloudrck** [mojeda/QuickGallery#2]
The software does not seem to care where you look for an image file. Simple GET manipulation can allow anyone to look for image files on the server.

Example:
Two users or vhosts
**/home/user1** _(QuickGallery at /home/user1/public_html/site/QuickGallery/index.php)_
**/home/user2** _(Image at /home/user2/test/img.jpg)_
<code>
http://example.com/site/QuickGallery/index.php?gallery=../../../../user2/img.jpg
</code>

**Comment by mojeda** [comment]
Fixed, by stripping forward slashes from $gallery.

Simply add:
$gallery = str_replace(chr(47), '', $gallery);
after $gallery = $_GET['gallery'];
