### ISSUE TITLE
Forward/Backward outline shows within image when mouse held down

### ISSUE THREAD

**Issue by tyeeman** [mojeda/QuickGallery#5]
As the title says I see an outline of the area that determines whether to go forward or backward to the next/previous image when the mouse is held down while clicking. I'm sure everyone sees it. Any solution?

**Comment by mojeda** [comment]
QuickGallery uses FancyBox: http://fancybox.net/ to generate the image popups, we don't modify or override any of the fancybox files.

That being said I can't reproduce this. It sounds like whatever browser you are using is putting the outline around the click areas for navigating back and forward however this is not an issue with QG.

If you still think it's an issue with QG please attach a screenshot and/or a link to your QG location so I may investigate.

Thanks!
